### ISSUE TITLE
"name 'lookup' is not defined"

### ISSUE THREAD

**Issue by VvizardDev** [UMNFuN/FUNGuild#13]
Hi there,
I'm having trouble running the FunGuild script. When I run on the terminal:

python funguild.py -db fungi -otu /home/qiime/USEARCHWHOLEDATASET/table_tax.biom -m

I get the following output:

"FunGuild v1.0 Beta
Downloading fungi database ...

Reading in the OTU table: '/home/qiime/USEARCHWHOLEDATASET/table_tax.biom'

Traceback (most recent call last):
  File "funguild.py", line 203, in <module>
    index_tax = header.index(lookup)
NameError: name 'lookup' is not defined"

I am at a loss as to what the actual error is, could it be I need to redownload the python script?
Any help would be appreciated.

Many thanks

Pascal

**Comment by ZeweiSong** [comment]
Hi, Pascal

It seems you are using a biom format OTU table as input. At this moment, the script only support text-based input. You can simple use "biom convert" to convert your OTU table into a tab-delimited file as input.

Zewei

**Comment by VvizardDev** [comment]
I've tried inputting a .txt biom file, it's still coming out with the same error:

FunGuild v1.0 Beta
Downloading fungi database ...

Reading in the OTU table: '/home/qiime/USEARCHWHOLEDATASET/table_tax.txt'

Traceback (most recent call last):
  File "funguild.py", line 203, in <module>
    index_tax = header.index(lookup)
NameError: name 'lookup' is not defined


Any ideas on what is going wrong?

Thanks

Pascal

**Comment by ZeweiSong** [comment]
Hi, Pascal

If you can send me an example OTU file, I can take a look.

My email is songzewei@outlook.com

Zewei
