### ISSUE TITLE
Issues taking values from database

### ISSUE THREAD

**Issue by lmichelo** [UMNFuN/FUNGuild#15]
The script wasn't able to concatenate str and int values from the database. Maybe the database has changed formats. The issue was resolved by forcing the script to turn each value into a string before concatenating with the for loop (around line 154; see change section 

below)

`for item in parse_data:
     line = ""
     for value in item:
         line+=str(value)+"\t"
     #f.write("%s\n" %("\t".join(item)))
     line+="\n"
     f.write(line)
 f.close()`

**Comment by ZeweiSong** [comment]
Thanks, Imichelo!
I've change the output code to convert all element to str before output.
