### ISSUE TITLE
FUNGuild online 

### ISSUE THREAD

**Issue by gcuster1991** [UMNFuN/FUNGuild#16]
When i upload my OTU table online and try to download the output OTU file i recieve the following error message:

Warning: fopen(/home/azfungiserv/stbates.org/guilds/otu_tables/otu_table_ITS2_tsv.guilds.txt): failed to open stream: No such file or directory in /home/azfungiserv/stbates.org/guilds/download.php on line 11

Warning: fclose() expects parameter 1 to be resource, boolean given in /home/azfungiserv/stbates.org/guilds/download.php on line 33

Any ideas as to what I'm doing wrong?

**Comment by ZeweiSong** [comment]
Have you try the script?

Zewei

--
Zewei Song
Postdoctoral Associate
University of Minnesota, Twin Cities
Department of Plant Pathology

Email: songzewei@outlook.com
Tel: 612-840-0267

**Comment by gcuster1991** [comment]
Yes.  I get this error:
matthewsMacBook:Spruce_Fungi_2 Gordon$ python Guilds_v1.0.py -otu /Users/Gordon/Desktop/Spruce_Fungi_2/otu_table_ITS2_tsv.txt -db fungi -m -u
FunGuild v1.0 Beta
Downloading fungi database ...

Reading in the OTU table: '/Users/Gordon/Desktop/Spruce_Fungi_2/otu_table_ITS2_tsv.txt'

Traceback (most recent call last):
  File "Guilds_v1.0.py", line 141, in <module>
    index_tax = header.index(lookup)
NameError: name 'lookup' is not defined

Im thinking my otu table is not in the correct format.  However, i am unsure how to get it formatted correctly.

**Comment by ZeweiSong** [comment]
You can take a look at the example otu table for the format.

Zewei
________________________________

**Comment by gcuster1991** [comment]
I found it. Thanks I had an extra row before my data.  I saw that was listed as a possible problem.  Thank you.
