### ISSUE TITLE
encoding

### ISSUE THREAD

**Issue by tobiasgf** [UMNFuN/FUNGuild#18]
Hi

I have been using FunGuild with succes. With my latest dataset, however, I had this error message

> Found 7676 matching taxonomy records in the database.  
Dereplicating and sorting the result...  
Traceback (most recent call last):  
  File "Guild11.py", line 295, in <module>  
    rec = '\t'.join([str(i) for i in item])  
UnicodeEncodeError: 'ascii' codec can't encode characters in position 95-96: ordinal not in range(128)  

I never really found out, what character in my input file (an output from UNITE) caused the problem but I solved by adding
> reload(sys)  
sys.setdefaultencoding('utf-8') 

to the script.

Cheers
Tobias

**Comment by ZeweiSong** [comment]
Hi, Tobias
Just try to output the entire OTU table, and avoid using the -match option. I haven't tweak that part for this encoding issue yet.

Zewei
