### ISSUE TITLE
funguild is down?

### ISSUE THREAD

**Issue by wcornwell** [UMNFuN/FUNGuild#19]
Hi!

I'm having trouble getting to http://funguild.org or stbates.org 

is that just me or is there a bigger issue?

**Comment by wcornwell** [comment]
Looks like it's my university's weird firewall.  closing for now...

**Comment by UMNFuN** [comment]
Hi Will:


Thanks so much for bringing this to my attention!


Your firewall may be needing some authentication - I added a self-signed SSL, which might help the situation (though you might still get a warning pop up).


This might take a while to propagate so try back in a bit and let me know the result either way.


Best.....


Cheers,

Scott
------------------------------------------
Scott T. Bates, PhD
Assistant Professor
Purdue University Northwest
North Central Campus
Dept. of Biological Sciences
(219) 785-5577
stbates@purdue.edu
http://stbates.org
------------------------------------------
________________________________

**Comment by wcornwell** [comment]
Hi Scott,

Sounds good.  I'm guessing 95% of the issue is on our end, and I've asked IT to look into it.  Will keep you posted. 

cheers,
Will
