### ISSUE TITLE
output missing a line ending?

### ISSUE THREAD

**Issue by tobiasgf** [UMNFuN/FUNGuild#20]
Hello

I find that in my output there is missing a line shift between the header and the first line - i.e. the last header, "Citation/Source" continues with the first OTU ID without any return/line-ending (or space, tab) in between.

Can you reproduce this "error"

**Comment by ZeweiSong** [comment]
Sometimes the "Carriahe return" in the text file generated under Windows system produces such kind of error. 

You can try to use the command dos2unix your_tab_delimited_otu_table.txt to remove the carriage return.

Let me know if it works!

Thanks for trying FUNGuild!
