### ISSUE TITLE
Guilds_v1.1.py error

### ISSUE THREAD

**Issue by iadamo1** [UMNFuN/FUNGuild#22]
Hi, I ran the python script on my OTU table and it worked, but I got a really messy output. So I thought i would take out the column that contained the sequence length information, as it is not present in example table that you provided. If I run the script again with this modification I get this error: 
 File "Guilds_v1.1.py", line 121, in <module>
    index_tax = header.index(lookup)
ValueError: 'taxonomy' is not in list

I am attaching the input file, I only took out a column and I did not modify the taxonomy one. 
thanks a lot for any help.
[CR_otutableID.txt](https://github.com/UMNFuN/FUNGuild/files/1593027/CR_otutableID.txt)

**Comment by ZeweiSong** [comment]
Hi, iadamo1

Can you post your command here? The format seems right.

Zewei

**Comment by bvaisvil** [comment]
I encountered a similar issue and removing all quotation characters (e.g. ") from my file fixed the issue.
