### ISSUE TITLE
Can not download the Output Files

### ISSUE THREAD

**Issue by cuihy608** [UMNFuN/FUNGuild#23]
Helllo Everyone,

I have a problem about FunGuild. When I finished the analysis, I can not download the the Output Files. It has no response to my download operation. 

![image](https://user-images.githubusercontent.com/51215377/59290285-84978f00-8c78-11e9-97ce-3652791af9e1.png)

Hope someone can help me. 

THANKS

**Comment by ZeweiSong** [comment]
Did you try to use the script?

Zewei

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Hburrill** [comment]
I am having the same issue. I use Firefox normally, but also tried in Google Chrome, as well as Microsoft Explorer. No luck. Explorer told me that the website couldn't be trusted, but I certainly trust anyone helping me identify fungal sequences!

Do you recommend using the python script instead?

**Comment by cuihy608** [comment]
I am sorry that I can not resolve the problem as the same in FunGuild. Hope to get the answer.


Best wishes







发件人：Hburrill <notifications@github.com>
发送日期：2019-07-28 22:24:44
收件人：UMNFuN/FUNGuild <FUNGuild@noreply.github.com>
抄送人：Haiying Cui <cuihy608@nenu.edu.cn>,Author <author@noreply.github.com>
主题：Re: [UMNFuN/FUNGuild] Can not download the Output Files (#23)
I am having the same issue. I use Firefox normally, but also tried in Google Chrome, as well as Microsoft Explorer. No luck. Explorer told me that the website couldn't be trusted, but I certainly trust anyone helping me identify fungal sequences!
Do you recommend using the python script instead?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.






Haiying Cui PhD
cuihy608@nenu.edu.cn
Address:5268 Renmin St., Changchun, Jilin Province, China
Telephone:
Cellphone:+86-18744045176

**Comment by ZeweiSong** [comment]
yes

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by xiaotuxiaotu520** [comment]
Hi all,
I have the same problem regarding the output file here, any solutions?

Best regards,
Minhuang

**Comment by cuihy608** [comment]
Hi All,
I have resolved the problem, my problem is the format of OTUs. You can strictly re-organize your data according to the example in the Website, maybe you can find a good results.


Best


Haiying






发件人：xiaotuxiaotu520 <notifications@github.com>
发送日期：2020-01-14 19:57:51
收件人：UMNFuN/FUNGuild <FUNGuild@noreply.github.com>
抄送人：Haiying Cui <cuihy608@nenu.edu.cn>,Author <author@noreply.github.com>
主题：Re: [UMNFuN/FUNGuild] Can not download the Output Files (#23)
Hi all,
 I have the same problem regarding the output file here, any solutions?
Best regards,
 Minhuang
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.






Haiying Cui PhD
cuihy608@nenu.edu.cn
Address:5268 Renmin St., Changchun, Jilin Province, China
Telephone:
Cellphone:+86-18744045176

**Comment by shiyun09** [comment]
Hi All.
I also encountered the same problem, and solved it following cuihy608's suggestion.
Good luck.



> Hi All, I have resolved the problem, my problem is the format of OTUs. You can strictly re-organize your data according to the example in the Website, maybe you can find a good results. Best Haiying 发件人：xiaotuxiaotu520 <notifications@github.com> 发送日期：2020-01-14 19:57:51 收件人：UMNFuN/FUNGuild <FUNGuild@noreply.github.com> 抄送人：Haiying Cui <cuihy608@nenu.edu.cn>,Author <author@noreply.github.com> 主题：Re: [UMNFuN/FUNGuild] Can not download the Output Files (#23) Hi all, I have the same problem regarding the output file here, any solutions? Best regards, Minhuang — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Haiying Cui PhD cuihy608@nenu.edu.cn Address:5268 Renmin St., Changchun, Jilin Province, China Telephone: Cellphone:+86-18744045176
