### ISSUE TITLE
encoding

### ISSUE THREAD

**Issue by jess-mackay** [UMNFuN/FUNGuild#24]
I am trying to use FUNGuild for the first time and I am getting the following error:
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 67: ordinal not in range(128)
My OTU table is attached. It was originally made in qiime2 then edited in excel/text editor to correctly format for FUNGuild.
I have tried running the FUNGuil script both with and without the -m option.
[table-with-taxonomy-mod.txt](https://github.com/UMNFuN/FUNGuild/files/3387601/table-with-taxonomy-mod.txt)

**Comment by ZeweiSong** [comment]
Hi, Jessica

How is the version of Python you are using? This unicode error is for Python 2.7.

We recommend all to use Python 3.6 or higher. If you don't have a preference, I personally prefer the Anaconda distribution.

Hope this.can fix your issue, let us know.

P.s. Thanks for usibg our tool!

Zewei

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jess-mackay** [comment]
Thanks, using 3.6 Anaconda fixed the issue.
