### ISSUE TITLE
newline characters missing

### ISSUE THREAD

**Issue by MWSchmid** [UMNFuN/FUNGuild#25]
Hi there

There are some newline characters missing in the python script. The following lines should be (at the moment the "\n" is missing):

Line 290: output.write('%s\n' % ('\t'.join(header))) #Header

Line 296: output.write('%s\n' % rec)

Line 323: output_unmatched.write('%s\n' % ('\t'.join(header)))

Best regards,

Marc

**Comment by ZeweiSong** [comment]
Thanks, Marc

I've added your fix to the script.
