### ISSUE TITLE
SyntaxError 

### ISSUE THREAD

**Issue by mlvermeire** [UMNFuN/FUNGuild#26]
Dear contributors,

I am very interested to use FUNGuild on my ITS DNA results, it looks like a great tool.
I have been trying to run the script, but so far without success. I would really appreciate some help. Here is what I did :
- I installed anaconda, with python 3.7.4
- I created a directory for FunGuild and saved the sequence table (OTU as rows - Unite database, with "taxonomy" as first column name, and samples as columns) as well as the script "Guilds_v1.0.py".
- In my windows Command prompt, i typed "python Guilds_v1.0.py -otu C:\Users\Username\Desktop\anacondatest\Seqtab_funguild.txt -db fungi"

But I received the following error: 
File "Guilds_v1.0.py", line 113
    print "FunGuild v1.0 Beta"
                             ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("FunGuild v1.0 Beta")?

I am not very familiar with python (I work with R), so I don't feel confident to start modifying your script. Do you know what might be the problem ?

Thank you very much in advance for your help!

Kind regards

Marie-Liesse

**Comment by hyphaltip** [comment]
I think you need to run w Python 2 or the funguild code needs to be updated for python 3.

Jason Stajich, PhD
jasonstajich.phd@gmail.com

**Comment by ZeweiSong** [comment]
Hi, All

There is a v1.1 version which is running under Python 3.

获取 Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by mlvermeire** [comment]
Dear Dr Zewei Song,

Thank you very much for your answer! 
I tried the v1.1 and the example OTU table from your website, and it worked with python 3. I obtained a nice txt file with the functions.

However, when I tried with my otu table, I received an error: 
Traceback (most recent call last):
  File "Guilds_v1.1.py", line 166, in <module>
    index_tax = header.index(lookup)
ValueError: 'taxonomy' is not in list

I think I didn’t manage to create the right format for my OTU table. I added a “taxonomy” column to my ITS sequence table, and followed the instructions on your website (I saved a small subsection of my sequence table, so you can have a look: “Funguild_test”). My taxonomy looks like this: 
“k__Fungi;p__Ascomycota;c__Sordariomycetes;o__Hypocreales;f__Nectriaceae;g__Fusarium;s__Fusarium_solani”
but yours look like this: 93.6%|Laetisaria_fuciformis|EU118639|SH012042.06FU|reps_singleton|k__Fungi;p__Basidiomycota;c__Agaricomycetes;o__Corticiales;f__Corticiaceae;g__Laetisaria;s__Laetisaria_fuciformis

How can I make my taxonomy fit with the official database taxonomy references used by Funguild? or do you think there is another formatting problem? 

Thank you very much in advance for your answer.

Kind regards

Marie-Liesse

[Funguild_test.txt](https://github.com/UMNFuN/FUNGuild/files/3845956/Funguild_test.txt)
