### ISSUE TITLE
Errors when trying to use Funguild

### ISSUE THREAD

**Issue by MarwaElnaiem** [UMNFuN/FUNGuild#28]
Dear All, 
I'm trying to use Funguild with my data , using Anaconda python and the funguildv1.1 script. 
My OTUs table does not contain the percentage and the accession number infront of the taxon as in the example otu table. 
The command as follows: 
(qiime2-2019.10) marwa@x86_64-conda_cos6-linux-gnu[ITS_tutorial] python Guilds_v1.1.py -otu /home/marwa/ITS_tutorial/otu_funguild_new.txt -m -u

I obtained the following result with the Value Error taxonomy is not in list. 
FunGuild v1.0 Beta
Connecting with FUNGuild database ...

Reading in the OTU table: '/home/marwa/ITS_tutorial/otu_funguild_new.txt'

Traceback (most recent call last):
  File "Guilds_v1.1.py", line 184, in <module>
    index_tax = header.index(lookup)
ValueError: 'taxonomy' is not in list

When i tried funguildv1.0 scrript with the python 2.7, i obtained this error: 
FunGuild v1.0 Beta
Downloading fungi database ...
Traceback (most recent call last):
  File "Guilds_v1.0.py", line 147, in <module>
    current = ast.literal_eval(line)
  File "/usr/lib/python2.7/ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    { "_id" : { "$oid" : "59271664791497fd28ec2597"} , "taxon" : "Dactylospora microspora" , "taxonomicLevel" : 20 , "trophicMode<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 
                                                                                                                                                          ^
SyntaxError: invalid syntax

Would you please helpme in that.
Regards, 
Marwa

**Comment by MarwaElnaiem** [comment]
Hey, 
I did fix the problem simply by renaming the first column heading from OTU ID to OTU_ID. 
I put it like that as it is in the OTU table example file. IT should be amended to OTU_ID in the example file.

**Comment by ZeweiSong** [comment]
Hi, Marwa

I think the space between OTU and ID was splitted by the script, so that you have one more column in the headers.

Zewei

--
宋泽伟 Zewei Song
华大生命科学研究院 宏基因组研究所 环境生态实验室
BGI-Shenzhen
Institute of Metagenomics
Lab of Environmental Ecology
电话 Tel: +86 13632929180
邮件 Email: songzewei@genomics.cn<mailto:songzewei@genomics.cn>
邮件 Email: songzewei@outlook.com

**Comment by MarwaElnaiem** [comment]
Hi, 
Yes, this was the case. 
Thank you
