### ISSUE TITLE
UnicodeEncodeError with  f.write('%s\n' % output_line) function

### ISSUE THREAD

**Issue by ejdiaz3** [UMNFuN/FUNGuild#30]
Hi 

I am using Anaconda 3 and Python 3.6 but I am getting an EncodeError. 

Traceback (most recent call last):
  File "Guilds_v1.1.py", line 351, in <module>
    f.write('%s\n' % output_line)
  File "C:\Users\Emily\anaconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0159' in position 593: character maps to <undefined>

Can you help?

Thank you, 
Emily

**Comment by ZeweiSong** [comment]
Hi, Emily

Can you make sure you are using Python 3 by checking its version?

Sometimes you can have more than one version running under your env.

Cheers,

Zewei

--
宋泽伟 Zewei Song
华大生命科学研究院 宏基因组研究所 环境生态实验室
BGI-Shenzhen
Institute of Metagenomics
Lab of Environmental Ecology
电话 Tel: +86 13632929180
邮件 Email: songzewei@genomics.cn<mailto:songzewei@genomics.cn>
邮件 Email: songzewei@outlook.com

**Comment by ejdiaz3** [comment]
Hi Zewei, 

Thank you for your quick answer. 

I double-check, and I have Python 3 (Python 3.6.10 |Anaconda, Inc.|). 

The thing is that the code runs well until it has to write any of the output files. After the code crash, I can go to my folder and find the "Matched Guilds" or the "Guilds" files (depending on the parameter I used in the code). However, the files never have all the information. 

With that information, do you know where I could be making an error?

Emily

**Comment by ejdiaz3** [comment]
Ok, I have an update. 

I was running the script in a Windows and was not working. I ran the script in Linux, and it just ran fine.

I guess the error is related to the operating system, not the script. 

Thank you anyway :)
