### ISSUE TITLE
web FUNGuild does not work anymore?

### ISSUE THREAD

**Issue by jcaguayo** [UMNFuN/FUNGuild#31]
Hello,
I'm trying to use the web site of FUNGuild, which is nice to test on little datasets. However the web application doesn't weem to work anymore, as it is not possible to upload our datasets. Is this a temporary issue or the web application will not anymore be available?
Thank for your answer.
Greetings,
jaime

**Comment by ZeweiSong** [comment]
Hi, Jaime

Have you tried the script yet?

Zewei

--
宋泽伟 Zewei Song
华大生命科学研究院 宏基因组研究所 环境生态实验室
BGI-Shenzhen
Institute of Metagenomics
Lab of Environmental Ecology
电话 Tel: +86 13632929180
邮件 Email: songzewei@genomics.cn<mailto:songzewei@genomics.cn>
邮件 Email: songzewei@outlook.com

________________________________

**Comment by UMNFuN** [comment]
Hello Jaime:

Sorry about the delay (and thanks for your speedy reply Zewei - I hope that all is well with you and yours).

Zewei is correct, we highly recommend that you use the Python script versions of FUNGuild - see: https://github.com/UMNFuN/FUNGuild
[https://avatars3.githubusercontent.com/u/7748151?s=400&v=4]<https://github.com/UMNFuN/FUNGuild>
UMNFuN/FUNGuild<https://github.com/UMNFuN/FUNGuild>
FUNGuild: parsing OTUs into functional guilds. Contribute to UMNFuN/FUNGuild development by creating an account on GitHub.
github.com
This past year I removed references to the online tool from the website as A) we are encouraging use of the script; and B) it has become difficult to support the online tool.

This being said, I left the old online version up as I knew that some folks still wanted to access it for use. As it sounds like it may now be broken, it might be time to take it down completely.

Also, we are beta testing a R version of the script as well (perhaps a bit slower, but still providing good results) - let me know if you are interested in beta testing that script and I can send it to you.

Thanks for your understanding in this mater - wishing you (in these times) all the best in research and health.

Scott T. Bates, PhD
Dept. of Biological Sciences
Purdue University Northwest
Westville Campus
(219) 785-5577
stbates@purdue.edu
http://stbates.org
________________________________
