### ISSUE TITLE
Output rearranges samples

### ISSUE THREAD

**Issue by wlwhalley** [UMNFuN/FUNGuild#32]
Hi, 

Everything works perfectly, except the output file is reordered differently from the input file in terms of sample order.

For example:
OTU
1
2
3

Becomes
OTU
2
1
3

Does the output file order alphabetically automatically? And is there a way to stop it doing so? 
I'm trying to import these outputs into a phyloseq object and the order is important

**Comment by ZeweiSong** [comment]
You can sort it in Excel if your table is small.

The shell command sort will also work.

Zewei

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
