### ISSUE TITLE
Using FUNGuild in R

### ISSUE THREAD

**Issue by EcoGinger** [UMNFuN/FUNGuild#34]
Hi All!

I am wondering if any of you all have used the FUNGuild database in R instead of Python. I have found mention of people getting it to work using phyloseq in R, but have not been able to find any instructions anywhere. 

Thanks in advance!

**Comment by wlwhalley** [comment]
Hi, 

Yes I've managed to crowbar funguild data into R by essentially treating it as taxonomic information so that the phylum etc columns in the phyloseq object ends up at the trophic mode and guild columns in the phyloseq output. 

I used the following code:

```
#Read in OTU table with guild info (created using python)
trop_tab = read.csv("C:/VMshared/FUNguild/taxconcguilds.csv", header = TRUE)

#Change values within Tropic.Mode column to "Undefined" for missing values and for those with the Confidence Level is "Possible", we are going to keep only those labeled "Probable" and "Highly Probable"
trop_tab$trophic_mode <- as.character(trop_tab$trophic_mode)
trop_tab$guild <- as.character(trop_tab$guild)
trop_tab$guild[trop_tab$guild == "-"] <- "Undefined"
trop_tab$trophic_mode[trop_tab$trophic_mode == "-"] <- "Undefined"
trop_tab$trophic_mode[trop_tab$confidence == "Possible"] <- "Undefined"


#Reduce guild table to OTU names and guilds
keep <- c("OTU_ID", "trophic_mode", "guild")
trop_table <- trop_tab[keep]

#Change OTUs to row names
rownames(trop_table) <- trop_table$OTU_ID
trop_table[1] <- NULL

#Create new "tax table" with just the guild data in it
fitGTR<-readRDS("C:/VMshared/analysis/treeits_prefilt.rds")
seqtab<-readRDS("C:/VMshared/analysis/seqtab_ITSpair_final1.rds")
metadata_ITS <- read.csv("C:/VMshared/master/master.csv", row.names=1)
TROP = tax_table(as.matrix(trop_table))
tax<- TROP

#Assign new 'tax table' to the old phyloseq object
ps <- phyloseq(otu_table(seqtab, taxa_are_rows=FALSE), 
               sample_data(metadata_ITS), 
               tax_table(tax),phy_tree(fitGTR$tree))
ps

```
There must be a better way to do it as this feels a bit messy, but I havent found one! 
```

```

**Comment by EcoGinger** [comment]
Hi @wlwhalley ! 

Thanks for your response! I emailed Faye Smith and she sent me very similar code to do the same thing. There may be a cleaner way of doing this, but in the end the resulting figure looks exactly like those that I am seeing published that use python instead of R.

**Comment by UMNFuN** [comment]
Hello EcoGinger and wlwhalley:

I have an rFunGuild.R script that a few folks have been beta testing.

The last I checked; it was running without issues.

It applies a very similar strategy as the python script (though it might be a tiny bit slower).

The results, however, should be the same (as both scripts ultimately depend on the entire FUNGuild db as accessed via the Restful API).

Please send me an email (stbates@purdue.edu), if you'd like to help in beta testing rFunGuild.R.

Scott T. Bates, PhD
Dept. of Biological Sciences
Purdue University Northwest
http://stbates.org
________________________________

**Comment by EcoGinger** [comment]
Hello @UMNFuN! 
Thank you for your offer. I would love to beta test it. I'll send you an email shortly.
