### ISSUE TITLE
First stepts in FunGuild

### ISSUE THREAD

**Issue by EJMA2020** [UMNFuN/FUNGuild#35]
Dear all,
I am starting user of python and FunGuild.
I have followed the script Guilds_v1.1. modifying the corresponding parameters as:
#Detect delimiter in the input file
#output files
In order to note my folders and the example otu table provider by developers:

I started to compute in Windows through cmd command line and as soon as it starts the following error appeared:
"name "argparse" is not defined".

If you could clarify what is happening would be great for beginners as me.

Thank

**Comment by ZeweiSong** [comment]
Can you post the full error message here. We would like to know exactly what you did in order to figure it out.

Cheers,

Zewei

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
