### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by hansammitz** [UMNFuN/FUNGuild#43]
Hi there

trying to run Guilds_v1.1.py and got the following error:

Guilds_v1.1.py:92: DeprecationWarning: 'U' mode is deprecated
  with open(otu_file, 'rU') as f1:
FunGuild v1.0 Beta
Connecting with FUNGuild database ...
Traceback (most recent call last):
  File "Guilds_v1.1.py", line 128, in <module>
    current_record = json.loads(record)
  File "/home/solo/miniconda3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/solo/miniconda3/lib/python3.7/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 436 (char 435)

this same error has occurred trying to run this script on 3 different machines (Linux/PC/Mac)

script was last run about 6 months ago with no issues

any solutions?

Many thanks

**Comment by janelucas** [comment]
I have had this same issue. 

How were you able to solve it?

**Comment by hansammitz** [comment]
Hi JaneThe json decode error occurs when you run an outdated version of the Guilds script.I grabbed the new one off the github page and that solved it.Cheers HansSent from my SAMSUNG Galaxy S7 on the Telstra Mobile Network
-------- Original message --------From: janelucas <notifications@github.com> Date: 24/2/21  10:02 am  (GMT+10:00) To: UMNFuN/FUNGuild <FUNGuild@noreply.github.com> Cc: hansammitz <hansammitz@gmail.com>, State change <state_change@noreply.github.com> Subject: Re: [UMNFuN/FUNGuild] JSONDecodeError (#43) 
I have had this same issue.
How were you able to solve it?
