### ISSUE TITLE
Issues with Guilds_v1.1.py calling Taxon

### ISSUE THREAD

**Issue by hansammitz** [UMNFuN/FUNGuild#46]
Hi there

Since downloading the new Guilds script i've found that I get a very different output when running my ITS1 dataset through the database.

It appears to be calling higher Taxon Levels for sequences that are classified to species
for example: 
k__Fungi;p__Basidiomycota;c__Agaricomycetes;o__Agaricales;f__Cortinariaceae;g__Cortinarius;s__Cortinarius_iringa;Cortinarius_iringa;
receives the Taxon 'Agaricales', (Taxon Level 7), whereas the previous script version annotated it as 'Cortinaruis' (Taxon Level 13)

This changes the output substantially - these taxa (and many more like it) now receive 'Possible' confidence levels of 'Pathotroph-Saprotroph-Symbiotroph', instead of 'Highly Probable'  'Symbiotroph'

has the database changed or is the script pulling something out incorrectly?

I would appreciate any help with this

Many thanks
Hans

**Comment by brendanf** [comment]
It looks like the script isn't properly choosing the lowest ranked taxon which matches your query.  I've submitted a pull request (#47); you can get the [updated script](https://raw.githubusercontent.com/UMNFuN/FUNGuild/f7f2175e576ab671ded81f56bb3e3cc5b9a7d470/Guilds_v1.1.py) there.  Alternatively, [FUNGuildR](https://github.com/brendanf/FUNGuildR) has the correct behavior.

**Comment by brendanf** [comment]
But note, you will still get superficially similar behavior with some other taxa, e.g. *Amanita*, which will also be annotated according to Agaricales, due to #44. (The entries for Amanita and Amanitaceae are actually absent from the new database.)
