### ISSUE TITLE
Running from R script

### ISSUE THREAD

**Issue by DGladish** [UMNFuN/FUNGuild#49]
Hi there! 

I am trying to run the FUNGuild script from an R script but I am having little success. I have tried using **system(python /GuildScript/Location/Guilds_v1.1.py -otu /specify/otu/location/otu_table_example.txt -db fungi -m -u)**, but it did not work. Do you have any suggestions as to how one could possibly run the FUNGuild script through R?

Thanks! :)

**Comment by brendanf** [comment]
I maintain a separate (unofficial) R version of the script, [FUNGuildR](http://github.com/brendanf/FUNGuildR), which you may want to check out.

**Comment by DGladish** [comment]
Thank you for the suggestion Brendan! I will check it out.

**Comment by DGladish** [comment]
Hi Brandon. I tried to run **library("FUNGuildR)** on line 21 of the README.Rmd file after running the other code in the chunk before it, but it wouldn't let me open the package. 

I tried doing **install.packages("FUNGuildR")**, but it said **Warning in install.packages : package 'FUNGuildR' in not available (for R version 3.5.1)**, which is the R version my organization uses. I attempted to find an older version of the FUNGuildR package on the CRAN package archive, but didn't find anything there. Is there any way I could use this script on R version 3.5.1?

Thanks again!

**Comment by brendanf** [comment]
@DGladish It's probably better to ask about FUNGuildR at its [own Issues page](https://github.com/issues) rather than here, but in short the answer is `devtools::install_github("brendanf/FUNGuildR")`.

**Comment by DGladish** [comment]
Hi Brendan,

I will do so in the future if I run into any more problems. I have resolved my issue. I found out that my devtools package was missing a dependency. FUNGuildR is now working for me with no issues. Thank you very much for your help :)
