### ISSUE TITLE
R script for FunGuild

### ISSUE THREAD

**Issue by LauraBMar** [UMNFuN/FUNGuild#50]
Dear Scott T. Bates, 
I used to use the FunGuild online tool with my data but I see that it is not available anymore. 
I have read in this post (https://github.com/UMNFuN/FUNGuild/issues/31#issuecomment-621427708) that you were working on an R script to use FunGuild. 
I have never worked with phyton and I am finding problems to run the script. Would it be possible to have the R script available?
Thank you for your help, and for developing this useful database!

Laura

**Comment by brendanf** [comment]
I don't know what the progress is on the official FUNGuild R script is, but you may be interested in the [FUNGuildR](https://github.com/brendanf/FUNGuildR) package.

**Comment by LauraBMar** [comment]
Dear Brendanf, 
This is exactaly what I was looking for. Thanks for your help :D
Laura
