### ISSUE TITLE
Database down?

### ISSUE THREAD

**Issue by brendanf** [UMNFuN/FUNGuild#74]
Apparently the FUNGuild database is down, both the full download (<http://stbates.org/funguild_db.php>) and the interactive web query version (<http://www.funguild.org/query.php>).  I just got notified about this today [via an issue](https://github.com/brendanf/FUNGuildR/issues/1#issuecomment-1556194596) so I don't know how long it has been ongoing.

**Comment by UMNFuN** [comment]
The issue should now be resolved.

Scott T. Bates, PhD
Nils K. Nelson Endowed Associate Professor
Dept. of Biological Sciences
Purdue University Northwest
(219)-785-5577
***@***.***
http://stbates.org
________________________________
From: brendanf ***@***.***>
Sent: Sunday, May 21, 2023 3:09 PM
To: UMNFuN/FUNGuild ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [UMNFuN/FUNGuild] Database down? (Issue #74)

CAUTION: This email originated from outside of the PNW environment. Do not click links or open attachments unless you recognize the sender and know the content is safe.


Apparently the FUNGuild database is down, both the full download (http://stbates.org/funguild_db.php<http://secure-web.cisco.com/1XE8RyLtbDHM8IL8MooM0mJGwDFskxb-4NqvAxhsHzO83UFEfbki9XwwoWVhhjNgvh6ti4AzN2YUwovTCILhp5LcJbNrtblwgU8pauwnMEBtRUuhLJ190gDvRTUFMdptH1Y7jLip4lHmefTZW8JXIQoaaJTzcafA6rFg0yknUpgJAUPtCklfF6O_fmHTQvcEjF75dF_TeZ6_qupqMYTRNcGpEpn67M97tV2FAAxgSYK7SbwGROSB3CnH1PHvsN8WtlMAhzmInaWk1mT6em385Kpxfu33dP5FJRGariAP-i7hCtoPT5BIJCDdY75Jt3rUMk0KnQp1UsfVX3XazSA50_iPdW6UuDfAeJU8rKU_Azffxbp6d-ksxc2Vlq89BeeGNC8sWAwGGTsCXQwQMlsLGNx-NMswBLJbkOlXmDYsyVeiObYh-Hn6ZTLph8fXUfGpM/http%3A%2F%2Fstbates.org%2Ffunguild_db.php>) and the interactive web query version (http://www.funguild.org/query.php). I just got notified about this today via an issue<https://github.com/brendanf/FUNGuildR/issues/1#issuecomment-1556194596> so I don't know how long it has been ongoing.

**Comment by brendanf** [comment]
Great, it is working again for me now.  Thanks Scott!
