### ISSUE TITLE
OTU delimiter parsing from alternate taxonomy input.

### ISSUE THREAD

**Issue by mikerobeson** [UMNFuN/FUNGuild#8]
Thank you for this great tool! I just wanted to point your attention to the `csv.Sniffer` functionality in the `Guilds_v1.0.py` code. It can sometimes miss-interpret what the actual OTU delimiter is, when using alternative taxonomies. That is, I used my pipeline [here](https://github.com/mikerobeson/Misc_Code/tree/master/SILVA_to_RDP) to generate QIIME compatible taxonomy files. However, the script `Guilds_v1.0.py` incorrectly detects the delimiter in these files to be `;` and not `\t`. I am assuming this is the case because I am keeping the full taxonomy information and this results far more `;` than `\t` characters in the file. I got around the issue by setting:

`otu_delimiter = dialect.delimiter` 
to 
`otu_delimiter = '\t'`

I think it would be great to allow an option to force override the delimiter setting.

-Thanks!
-M

**Comment by ZeweiSong** [comment]
Thanks for you input, Mike.
I guess for your OTU table you don't have many samples. So the number of taxonomic level out number the sample number, that fools the delimiter detecter.
I'll find a get around and fix this issue.

**Comment by mikerobeson** [comment]
@ZeweiSong Thanks! I have 51 samples. My code retains the full taxonomy from the SILVA database (i.e. not just the standard 7 ranks of k_;p_;c_;o_;f_;g_;s_). As a result, I can have more than 20 taxonomic ranks. Which, as we both noted, leads to much more `;` in the taxonomy strings than is typical. :-)

**Comment by ZeweiSong** [comment]
Now if the delimiter was determined to be ";", it will be changed to "\t". Thanks again for your input, Mike.
